- hosts: webservers
  become: yes
  gather_facts: no

  tasks:
    # tasks must be nested
    - name: Include user task
      ansible.builtin.import_tasks: ../tasks/web_create_user.yml

    - name: Include git task
      ansible.builtin.import_tasks: ../tasks/web_start_git.yml
      vars:
        title: "{{ git_title }}"

    - name: Include nginx task
      ansible.builtin.import_tasks: ../tasks/web_start_nginx.yml
