---
- hosts: webservers
  become: yes

  tasks:
   - name: instal nginx
     ansible.builtin.apt:
       name: nginx
       state: present

   - name: Template html file
     ansible.builtin.copy:
       src: files/index.html
       dest: /usr/share/nginx/html/index.html
     notify:
      - Restart nginx

   - name: Template configuration file
     ansible.builtin.copy:
       src: files/nginx.conf
       dest: /etc/nginx/nginx.conf
     notify:
       - Restart nginx

  handlers:
    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
